export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
export const UPDATE_CONNECTION_TYPE = 'UPDATE_CONNECTION_TYPE';
export const CHANGE_LANGUAGE='CHANGE_LANGUAGE'
export const GET_NEWS_FEEDS='GET_NEWS_FEEDS'

